# Generated by Django 2.0.1 on 2018-01-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('colleges', models.ManyToManyField(to='tutorials.College')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTutorialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tutorials.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('colleges', models.ManyToManyField(to='tutorials.College')),
            ],
        ),
        migrations.AddField(
            model_name='studenttutorialstatus',
            name='tutorial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tutorials.Tutorial'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttutorialstatus',
            unique_together={('tutorial', 'student')},
        ),
    ]
