# Generated by Django 2.0.1 on 2018-01-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='tutorials.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tutoriallink',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutorials.Tutorial'),
        ),
    ]
