# Generated by Django 2.0.1 on 2018-01-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTutorial',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('tutorials.tutorial',),
        ),
        migrations.AlterModelOptions(
            name='studenttutorialstatus',
            options={'verbose_name': 'Tutorial Enrollment', 'verbose_name_plural': 'Manage Enrollments in your Tutorials'},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name': 'Tutorial', 'verbose_name_plural': 'Browse All Tutorials'},
        ),
    ]
