# Generated by Django 2.0.1 on 2018-01-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20180129_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttutorialstatus',
            options={'verbose_name_plural': 'Student-tutorial statuses'},
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='owner',
        ),
    ]
