# Generated by Django 2.0.1 on 2018-01-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20180130_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytutorial',
            options={'verbose_name': 'Tutorial/Request', 'verbose_name_plural': 'My Tutorials and Requests'},
        ),
        migrations.AlterModelOptions(
            name='tutoriallink',
            options={'verbose_name': 'Inspiration/Resource Link', 'verbose_name_plural': 'Inspiration/Resource Link'},
        ),
    ]
