# Generated by Django 2.0.1 on 2018-02-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20180130_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttutorialstatus',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='prerequisites',
            field=models.TextField(default='Not yet', max_length=1000),
            preserve_default=False,
        ),
    ]
