# Generated by Django 2.0.1 on 2018-01-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20180129_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='tutorials.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=2),
        ),
    ]
