# Generated by Django 2.0.1 on 2018-01-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20180129_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='colleges',
            new_name='majors',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='owner',
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studenttutorialstatus',
            name='status',
            field=models.CharField(choices=[('O', 'Owner'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1),
        ),
    ]
