# Generated by Django 2.0.1 on 2018-02-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_tutorial_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttutorialstatus',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
