# Generated by Django 2.0.1 on 2018-01-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20180129_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='owner',
        ),
        migrations.AlterField(
            model_name='studenttutorialstatus',
            name='status',
            field=models.CharField(choices=[('O', 'Owner'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1),
        ),
    ]
